<?php

use App\Models\CandidateProfile;
use App\Models\JobPosting;

return [
    'driver' => env('SCOUT_DRIVER', 'collection'),

    'prefix' => env('SCOUT_PREFIX', ''),

    'queue' => (bool) env('SCOUT_QUEUE', false),

    'after_commit' => (bool) env('SCOUT_AFTER_COMMIT', true),

    'chunk' => [
        'searchable' => (int) env('SCOUT_CHUNK_SEARCHABLE', 500),
        'unsearchable' => (int) env('SCOUT_CHUNK_UNSEARCHABLE', 500),
    ],

    'soft_delete' => false,

    'identify' => false,

    'meilisearch' => [
        'host' => env('MEILISEARCH_HOST', 'http://localhost:7700'),
        'key' => env('MEILISEARCH_KEY'),
        'index-settings' => [
            CandidateProfile::class => [
                'searchableAttributes' => [
                    'current_position',
                    'desired_position',
                    'summary',
                    'occupation_names',
                    'skill_names',
                    'skill_slugs',
                    'language_names',
                    'language_codes',
                    'highest_qualification',
                    'driving_licenses',
                ],
                'filterableAttributes' => [
                    'id',
                    'current_country_code',
                    'occupation_id',
                    'skill_ids',
                    'skill_slugs',
                    'language_codes',
                    'language_levels',
                    'experience_years',
                    'employment_preferences',
                    'weekly_hours',
                    'travel_ready',
                    'relocation_ready',
                    'available_from_timestamp',
                    'salary_expectation_cents',
                    'salary_currency',
                    'requires_visa',
                    'has_work_permit',
                ],
                'sortableAttributes' => [
                    'experience_years',
                    'available_from_timestamp',
                    'salary_expectation_cents',
                    'published_at',
                ],
                'displayedAttributes' => [
                    'id',
                    'current_country_code',
                    'summary',
                    'current_position',
                    'desired_position',
                    'occupation_id',
                    'occupation_slug',
                    'occupation_names',
                    'skill_ids',
                    'skill_slugs',
                    'skill_names',
                    'language_codes',
                    'language_names',
                    'language_levels',
                    'experience_years',
                    'highest_qualification',
                    'driving_licenses',
                    'employment_preferences',
                    'weekly_hours',
                    'travel_ready',
                    'relocation_ready',
                    'available_from',
                    'available_from_timestamp',
                    'salary_expectation_cents',
                    'salary_currency',
                    'requires_visa',
                    'has_work_permit',
                    'published_at',
                ],
                'pagination' => ['maxTotalHits' => 1000],
            ],
            JobPosting::class => [
                'searchableAttributes' => [
                    'title',
                    'position',
                    'description',
                    'company_name',
                    'company_industry',
                    'occupation_names',
                    'skill_names',
                    'language_names',
                    'language_notes',
                    'location_city',
                ],
                'filterableAttributes' => [
                    'id',
                    'company_id',
                    'occupation_id',
                    'skill_ids',
                    'language_codes',
                    'language_levels',
                    'location_country_code',
                    'expected_experience_years',
                    'hours_min',
                    'hours_max',
                    'employment_type',
                    'compensation_min_cents',
                    'compensation_max_cents',
                    'currency',
                    'is_remote',
                    'visa_package_available',
                    'status',
                ],
                'sortableAttributes' => [
                    'expected_experience_years',
                    'compensation_min_cents',
                    'compensation_max_cents',
                    'boosted_until',
                    'published_at',
                ],
                'displayedAttributes' => [
                    'id',
                    'company_id',
                    'company_name',
                    'company_slug',
                    'company_industry',
                    'title',
                    'slug',
                    'position',
                    'description',
                    'occupation_id',
                    'occupation_slug',
                    'occupation_names',
                    'skill_ids',
                    'skill_names',
                    'language_codes',
                    'language_names',
                    'language_levels',
                    'language_notes',
                    'location_city',
                    'location_country_code',
                    'expected_experience_years',
                    'hours_min',
                    'hours_max',
                    'employment_type',
                    'compensation_min_cents',
                    'compensation_max_cents',
                    'currency',
                    'compensation_interval',
                    'status',
                    'is_remote',
                    'visa_package_available',
                    'boosted_until',
                    'published_at',
                ],
                'pagination' => ['maxTotalHits' => 1000],
            ],
        ],
    ],
];
